"use client";

import React from "react";
import { X, Loader2, AlertCircle, RefreshCw } from "lucide-react";

interface SummaryPanelProps {
  isOpen: boolean;
  isLoading: boolean;
  summary: string | null;
  error: string | null;
  fileName?: string;
  onClose: () => void;
  onRetry?: () => void;
  isCached?: boolean;
}

export const SummaryPanel: React.FC<SummaryPanelProps> = ({
  isOpen,
  isLoading,
  summary,
  error,
  fileName = "File",
  onClose,
  onRetry,
  isCached = false,
}) => {
  return (
    <>
      {/* Overlay */}
      {isOpen && (
        <div
          onClick={onClose}
          className="fixed inset-0 bg-black/40 z-40 backdrop-blur-sm"
        />
      )}

      {/* Side Panel */}
      <div
        className={`fixed right-0 top-0 bottom-0 w-full md:w-96 bg-white shadow-2xl z-50 transform transition-transform duration-300 ease-out overflow-y-auto ${
          isOpen ? "translate-x-0" : "translate-x-full"
        }`}
      >
        {/* Header */}
        <div className="sticky top-0 bg-white border-b border-slate-200/60 p-6 flex items-start justify-between">
          <div className="flex-1 pr-4">
            <h2 className="text-lg font-bold text-slate-800">AI Summary</h2>
            <p className="text-sm text-slate-500 mt-1 truncate">{fileName}</p>
            {isCached && (
              <p className="text-xs text-emerald-600 mt-2 font-medium">
                ✓ Cached summary
              </p>
            )}
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-slate-100 transition-colors flex-shrink-0"
            aria-label="Close panel"
          >
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          {isLoading ? (
            /* Loading State */
            <div className="flex flex-col items-center justify-center py-12">
              <div className="w-12 h-12 rounded-full border-4 border-indigo-200 border-t-indigo-600 animate-spin mb-4" />
              <p className="text-slate-600 font-medium">Generating summary...</p>
              <p className="text-sm text-slate-500 mt-2">
                Processing your file with AI
              </p>
            </div>
          ) : error ? (
            /* Error State */
            <div className="flex flex-col items-start space-y-4">
              <div className="flex items-start gap-3 p-4 rounded-xl bg-red-50 border border-red-200 w-full">
                <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <p className="font-semibold text-red-900 text-sm">
                    Failed to generate summary
                  </p>
                  <p className="text-sm text-red-700 mt-1">{error}</p>
                </div>
              </div>
              {onRetry && (
                <button
                  onClick={onRetry}
                  className="px-4 py-2 rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 transition-colors font-medium text-sm flex items-center gap-2"
                >
                  <RefreshCw className="w-4 h-4" />
                  Try Again
                </button>
              )}
            </div>
          ) : summary ? (
            /* Summary Content */
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-gradient-to-br from-indigo-50 to-purple-50 border border-indigo-200/60">
                <p className="text-slate-800 leading-relaxed text-sm">
                  {summary}
                </p>
              </div>
              <div className="text-xs text-slate-500 space-y-2 pt-2">
                <p className="font-semibold text-slate-600">About this summary:</p>
                <ul className="list-disc list-inside space-y-1">
                  <li>Generated by Google Gemini AI</li>
                  <li>Summarizes the key content of the file</li>
                  <li>Results are cached for faster access</li>
                </ul>
              </div>
            </div>
          ) : (
            /* No Summary */
            <div className="flex flex-col items-center justify-center py-8 text-center">
              <div className="w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center mb-4">
                <AlertCircle className="w-6 h-6 text-slate-400" />
              </div>
              <p className="text-slate-600 font-medium">No summary available</p>
              <p className="text-sm text-slate-500 mt-1">
                Unable to generate a summary for this file
              </p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 bg-white border-t border-slate-200/60 p-6">
          <button
            onClick={onClose}
            className="w-full px-4 py-2 rounded-lg bg-slate-100 text-slate-700 hover:bg-slate-200 transition-colors font-medium text-sm"
          >
            Close
          </button>
        </div>
      </div>
    </>
  );
};

export default SummaryPanel;
